### ISSUE TITLE
Filenames and numbers 

### ISSUE THREAD

**Issue by organised** [Processing-iOS/Processing-iOS#32]
Current version has an issue where when any name that includes a number is disallowed! 

Should allow numbers and underscores just like previous versions.

**Comment by frogg** [comment]
I have already fixed this bug in the current beta build on Testflight, so it should be part of the next release.
See Issue #20 for reference.

**Comment by organised** [comment]
Awesome! Thanks — I’m going to install the TestFlight version on a separate device so I don’t lose my existing sketches

**Comment by frogg** [comment]
It should keep your local files when you install the TestFlight version – it's like an app update so it does not actually remove any files but just replaces the app.
